spring:
  datasource:
    url: jdbc:mysql://localhost:3306/just4me?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

just4me:
  api-package: com.gxu.just4me.api

